name: aasd4011-assignment1-github-setup

on: [push, pull_request]

jobs:
  grade-project:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4


    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      run: |
        pytest
        
    - name: Autograding Action
      uses: uhafner/autograding-github-action@v3.19.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
          
